server:
local-zone: "duckduckgo.com." transparent
local-data: "duckduckgo.com. CNAME safe.duckduckgo.com."
local-zone: "www.duckduckgo.com." transparent
local-data: "www.duckduckgo.com. CNAME safe.duckduckgo.com."
local-zone: "start.duckduckgo.com." transparent
local-data: "start.duckduckgo.com. CNAME safe.duckduckgo.com."
local-zone: "duck.com." transparent
local-data: "duck.com. CNAME safe.duckduckgo.com." 
local-zone: "www.duck.com." transparent
local-data: "www.duck.com. CNAME safe.duckduckgo.com."
local-zone: "bing.com." transparent
local-data: "bing.com. CNAME strict.bing.com."
local-zone: "www.bing.com." transparent
local-data: "www.bing.com. CNAME strict.bing.com."
local-zone: "api.qwant.com." transparent
local-data: "api.qwant.com. CNAME safeapi.qwant.com."
local-zone: "www.qwant.com." transparent
local-data: "www.qwant.com. CNAME safeapi.qwant.com."
local-zone: "qwant.com." transparent
local-data: "qwant.com. CNAME safeapi.qwant.com."
local-zone: "s1.qwant.com." transparent
local-data: "s1.qwant.com. CNAME safeapi.qwant.com."
local-zone: "s2.qwant.com." transparent
local-data: "s2.qwant.com. CNAME safeapi.qwant.com."
local-zone: "pixabay.com." transparent
local-data: "pixabay.com. CNAME safesearch.pixabay.com."
local-zone: "www.youtube.com." transparent
local-data: "www.youtube.com. CNAME restrictmoderate.youtube.com."
local-zone: "m.youtube.com." transparent
local-data: "m.youtube.com. CNAME restrictmoderate.youtube.com."
local-zone: "youtubei.googleapis.com." transparent
local-data: "youtubei.googleapis.com. CNAME restrictmoderate.youtube.com."
local-zone: "youtube.googleapis.com." transparent
local-data: "youtube.googleapis.com. CNAME restrictmoderate.youtube.com."
local-zone: "www.youtube-nocookie.com." transparent
local-data: "www.youtube-nocookie.com. CNAME restrictmoderate.youtube.com."
local-zone: "yandex.com." transparent
local-data: "yandex.com. CNAME familysearch.yandex.ru."
local-zone: "www.yandex.com." transparent
local-data: "www.yandex.com. CNAME familysearch.yandex.ru."
local-zone: "yandex.ru." transparent
local-data: "yandex.ru. CNAME familysearch.yandex.ru."
local-zone: "www.yandex.ru." transparent
local-data: "www.yandex.ru. CNAME familysearch.yandex.ru."
local-zone: "yandex.ua." transparent
local-data: "yandex.ua. CNAME familysearch.yandex.ru."
local-zone: "www.yandex.ua." transparent
local-data: "www.yandex.ua. CNAME familysearch.yandex.ru."
local-zone: "yandex.by." transparent
local-data: "yandex.by. CNAME familysearch.yandex.ru."
local-zone: "www.yandex.by." transparent
local-data: "www.yandex.by. CNAME familysearch.yandex.ru."
local-zone: "yandex.kz." transparent
local-data: "yandex.kz. CNAME familysearch.yandex.ru."
local-zone: "www.yandex.kz." transparent
local-data: "www.yandex.kz. CNAME familysearch.yandex.ru."
